Repository lulav/citros_doc, pull requests merged in 2023-11, with the labels that each got.

#63 Doc/dockerfile
  .vscode/settings.json
  docs_tutorials/Dockerfile/dockerfile_overview.md
  docs_tutorials/Dockerfile/img/docker-system.jpeg
  docs_tutorials/Dockerfile/img/images.jpeg
  yarn.lock
Labels: documentation

#65 docs(docs_data_analysis/snippets): examples of snippets
  docs_data_analysis/index.md
  docs_data_analysis/snippets_doc/data_access/snippets_batch_content.md
  docs_data_analysis/snippets_doc/data_access/snippets_batches.md
  docs_data_analysis/snippets_doc/data_access/snippets_plotting.md
  docs_data_analysis/snippets_doc/data_access/snippets_query_data.md
  docs_data_analysis/snippets_doc/data_access/snippets_repositories.md
  docs_data_analysis/snippets_doc/data_access/snippets_users.md
  docs_data_analysis/snippets_doc/snippets_error_analysis.md
  docs_data_analysis/snippets_doc/snippets_validation.md
  docs_data_analysis_versioned_docs/version-v0.8.0/index.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/data_access/snippets_batch_content.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/data_access/snippets_batches.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/data_access/snippets_plotting.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/data_access/snippets_query_data.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/data_access/snippets_repositories.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/data_access/snippets_users.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/snippets_error_analysis.md
  docs_data_analysis_versioned_docs/version-v0.8.0/snippets_doc/snippets_validation.md
  docs_data_analysis_versioned_sidebars/version-v0.8.0-sidebars.json
  sidebarsDataAnalysis.js
Labels: enhancement

#72 fix(into to citros): some fixes
  docs_tutorials/image.png
  docs_tutorials/index.md
Labels: documentation

#78 docs (soft_landing):update
  docs_tutorials/soft_landing/img/image-1.png
  docs_tutorials/soft_landing/img/image-2.png
  docs_tutorials/soft_landing/img/image-4.png
  docs_tutorials/soft_landing/img/image-5.png
  docs_tutorials/soft_landing/img/image.png
  docs_tutorials/soft_landing/soft_landing.md
Labels: documentation, enhancement

#77 docs(mass-spring-damper-tutorial): update
  docs_tutorials/mass_spring_damper/mass_spring_damper.md
Labels: documentation, enhancement

#79 docs(docs_tutorials/gal_orbits): update according to the new template
  docs_tutorials/gal_orbits/gal_orbits.md
  docs_tutorials/gal_orbits/img/fig_ngc6316_ellipse.png
  docs_tutorials/gal_orbits/img/fig_ngc6316_test.png
  docs_tutorials/gal_orbits/img/fig_ngc6316_xy.png
Labels: documentation, enhancement
