Repository lulav/citros_doc, pull requests merged in 2023-12, with the labels that each got.

#76 docs(drone-tutorial): update to the new scheme
  docs_tutorials/drone/drone.md
Labels: documentation, enhancement

#92 feat(src/theme/CodeBlock/): copy code
  src/theme/CodeBlock/CopyButton/index.js
  src/theme/CodeBlock/Line/index.js
Labels: enhancement

#85 docs(docs_tutorials/pendulum): tutorial for the pendulum project
  docs_tutorials/pendulum/Pendulum.md
  docs_tutorials/pendulum/img/double_pendulum_schema.png
  docs_tutorials/pendulum/img/double_pendulum_xy.png
  docs_tutorials/pendulum/img/system_with_spring_schema.png
  docs_tutorials/pendulum/img/systems_schema.png
Labels: documentation
